runtime: nodejs18
service: default
env: standard

env_variables:
  INSTANCE_CONNECTION_NAME: etown-course-planner:us-east1:course-planner-db
  DB_USER: web-api
  DB_PASS: Oe,+SNbTmq0Gk;H(
  DB_NAME: course_planner
  OPENAI_API_KEY: openai-api-key
handlers:
  - url: /
    static_files: web_src/index.html
    upload: web_src/index.html
  
  - url: /index.html
    static_files: web_src/index.html
    upload: web_src/index.html

  # Stylesheet links
  - url: /stylesheets/index.css
    static_files: web_src/stylesheets/index.css
    upload: web_src/stylesheets/index.css

  - url: /stylesheets/login.css
    static_files: web_src/stylesheets/login.css
    upload: web_src/stylesheets/login.css

  - url: /stylesheets/report.css
    static_files: web_src/stylesheets/report.css
    upload: web_src/stylesheets/report.css

  - url: /stylesheets/schedule.css
    static_files: web_src/stylesheets/schedule.css
    upload: web_src/stylesheets/schedule.css
  
  # Inclusion links
  - url: /includes/navbar.html
    static_files: web_src/includes/navbar.html
    upload: web_src/includes/navbar.html

  - url: /includes/footer.html
    static_files: web_src/includes/footer.html
    upload: web_src/includes/footer.html

  - url: /images/profile.png
    static_files: images/profile.png
    upload: images/profile.png

  - url: /includes/main.js
    static_files: web_src/includes/main.js
    upload: web_src/includes/main.js

  - url: /includes/create.js
    static_files: web_src/includes/create.js
    upload: web_src/includes/create.js
  
  - url: /includes/login.js
    static_files: web_src/includes/login.js
    upload: web_src/includes/login.js

  - url: /includes/register.js
    static_files: web_src/includes/register.js
    upload: web_src/includes/register.js

  - url: /includes/report.js
    static_files: web_src/includes/report.js
    upload: web_src/includes/report.js
  
  - url: /includes/user.js
    static_files: web_src/includes/user.js
    upload: web_src/includes/user.js
  
  # Page links
  - url: /report.html
    static_files: web_src/report.html
    upload: web_src/report.html

  - url: /schedule.html
    static_files: web_src/schedule.html
    upload: web_src/schedule.html

  - url: /login.html
    static_files: web_src/login.html
    upload: web_src/login.html

  - url: /register.html
    static_files: web_src/register.html
    upload: web_src/register.html

  - url: /create.html
    static_files: web_src/create.html
    upload: web_src/create.html
  
  - url: /loggedin.html
    static_files: web_src/loggedin.html
    upload: web_src/loggedin.html