runtime: php83

service: default
env: standard

handlers:
- url: /
  script: index.php

- url: /navbar.php
  script: navbar.php

- url: /report.php
  script: report.php

- url: /schedule.php
  script: schedule.php

- url: /style.css
  static_files: style.css
  upload: style.css
